services:
  web:
    image: nginx:latest
    ports:
      - "10000:80"
      - "10001:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./docker/log/nginx:/var/log/nginx
    depends_on:
      - php
    restart: unless-stopped

  database:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "10010:3306"
    volumes:
      - ./docker/fs/mysql:/var/lib/mysql
      - .:/tmp:delegated
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/conf.d/redis.ini:/usr/local/etc/php/conf.d/redis.ini
      - ./docker/log/php:/var/log/php
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
    ports:
      - "10020:9000"
    depends_on:
      - database
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "10030:6379"
    volumes:
      - ./docker/fs/redis:/data
    restart: unless-stopped
